services:
  web:
    build: .
    # Прапорець --reload забезпечить автоперезапуск сервера при зміні коду
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    # Монтуємо поточну папку з комп'ютера в папку /code всередині контейнера
    volumes:
      - .:/code
    # Підключаємо твій файл .env, щоб Pydantic Settings побачив усі 6 потрібних змінних
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: